from enum import Enum
  
class PermisoAdminEnum(Enum):
  EDITAR_USUARIO = 1
  OBTENER_ROL = 2
  CREAR_ROL = 3
  EDITAR_ROL = 4
  CREAR_AREA = 5
  EDITAR_AREA = 6
  OBTENER_CATEGORIAS = 7
  CREAR_CATEGORIA = 8
  EDITAR_CATEGORIA = 9
  OBTENER_MODULOS = 10
  CREAR_MODULO = 11
  EDITAR_MODULO = 12
  OBTENER_FORMULARIOS = 13
  CREAR_FORMULARIO = 14
  EDITAR_FORMULARIO = 15
  
  
class RolEnum(Enum):
  SUPERADMINISTRADOR = 1
      