export const PERMISOS_ADMIN = {
  ADMIN_USUARIO: 1,
  ADMIN_AREA: 2,
  ADMIN_ROL_Y_PERMISO: 3,
  ADMIN_CATEGORIA: 4,
  ADMIN_MODULO: 5,
  ADMIN_FORMULARIO: 6,
};

export const TIPOS_CAMPO = {
  TEXTO: 1,
  NUMERO: 2,
  BOOLEANO: 3,
  FECHA: 4,
  SELECCION_UNICA: 5,
  SELECCION_MULTIPLE: 6,
  GRUPO_CAMPOS: 7,
  GEOMETRICO: 8,
};
